// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kskmoxfclbwfsiaucvwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtza21veGZjbGJ3ZnNpYXVjdndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzc0MDUsImV4cCI6MjA2MDIxMzQwNX0.5pIyenoh0HF6l1j9PifjDgMEwBv3HVWBRJ2Icr3Ic8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);